config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'
  get 'errors/internal_server_error'
  root 'items#index' 
  get '/home/contact', to: 'home#contact', as: 'contacts'
  get '/home/about_us', to: 'home#about_us', as: 'about_us'
  get '/home/faq', to: 'home#faq', as: 'faq'
  get '/add_to_carts/:id' => 'carts#additem', as: 'addtocart'
  get '/remove_from_carts/:id' => 'carts#removeitem', as: 'removefromcart'



  devise_for :users,
    :controllers => {:registrations => "registrations"},
    path: '',
    path_names: { sign_up: 'Create Account', sign_in: 'Login', sign_out: 'Logout', password: 'Reset Password'}
  devise_scope :user do 
    get "/my_profile" => "registrations#show"
    get "/my_profile/security" => "registrations#security"
    resources :wishlists

  end

  resources :reviews
  resources :items

  get '/carts/payment' => 'carts#payment'
  resources :carts
  resources :orders
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
end

app/models/cart.rb
class Cart < ApplicationRecord

  belongs_to :user
  belongs_to :order, optional: true
  belongs_to :item

  def total_per_item
		return self.quantity.to_i * Item.find_by_id(self.item_id).price.to_i
	end

 # ADD FUNCTION MINUS PLUS ARTICLE
 
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  before_action :auth_user

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.where(user_id: current_user.id).where(order_id: nil)
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = Cart.find(params[:id])
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @user = current_user.id
    @cart = Cart.new(cart_params)
    @cart.user_id  = current_user.id

    respond_to do |format|
      if @cart.save
        format.html { redirect_to root_path, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to request.referer, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def payment
    @order = Order.new
    @amount = 0
    @carts = Cart.where(user_id: current_user.id)
    i = 0

    Cart.where(user_id: current_user.id).each do |item_in_cart|
      i +=1
      @amount += item_in_cart.total_per_item
    end

    # En centimes
    @amount *= 100

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })

    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      #description renvoie a quel nom est cree le compte (details des payments visibles sur stripe directement, notament le nom)
      description: 'Rails Stripe customer',
      currency: 'EUR',
    })

    @order.stripe_id = params[:stripeToken]
    @order.user_id = current_user.id
    @order.save
    
    Cart.where(user_id: current_user.id).each do |item_in_cart|
        item_in_cart.update(order_id: @order.id)
    end    

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to :root
  end

  def additem
    @cart = Cart.find(params[:id])
    @qty = @cart.quantity + 1
    @cart.update(quantity: @qty)
    respond_to do |format|
      format.html { redirect_to request.referer, notice: 'Cart was successfuuuuuully saved.' }
      format.json { head :no_content }
    end
  end

  def removeitem
    @cart = Cart.find(params[:id])
    @qty = @cart.quantity - 1
    @cart.update(quantity: @qty)
    respond_to do |format|
      format.html { redirect_to request.referer, notice: 'Cart was successfuuuuuully saved.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(:item_id)
    end
    def auth_user
      redirect_to new_user_session_path unless user_signed_in?
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/index.html.erb
<!-- Page Title-->
<div class="page-title d-flex p-0 mb-3" aria-label="Page title">
  <div class="container text-left align-self-center">
    <h1 class="page-title-heading text-center">My Cart</h1>
  </div>
</div>

<!-- Page Content-->
<div class="container pb-5 mb-2">
  <!-- Cart Item-->
  <% @total = 0 %>
  <% @carts.order(:id).each do |cart| %>
    <div class="cart-item d-md-flex justify-content-between">
      <a class="featured-product" data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/carts/<%= cart.id %>">
        <span class="remove-item"><i class="fas fa-times"></i></span>
      </a>
      <div class="px-3 my-3">
        <a class="cart-item-product" href="shop-single.html">
          <div class="cart-item-product-thumb"><img class="test" src="<%= cart.item.image_url %>" alt="Product"></div>
          <div class="cart-item-product-info">
            <h4 class="cart-item-product-title"><%= cart.item.title %></h4>
            <span><strong>Category:</strong><%= Breed.find(Item.find(cart.item.id).breed_id).name %></span>
            <span><strong>Unit Price:</strong><%= cart.item.price.to_i %>.00€</span>
          </div>
        </a>
      </div>
      <div class="px-3 my-3 text-center">
        <div class="cart-item-label my-quantity">Quantity: <%= cart.quantity %> </div>
          <div class="btn-group" role="group" aria-label="Basic example">
            <% if cart.quantity == 1 %>
              <%= link_to raw("<i class=\"far fa-trash-alt\"></i>"), cart, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-secondary cminus" %>
            <% else %>
              <%= link_to raw("<i class=\"fas fa-minus\"></i>"), removefromcart_path(cart.id), method: "get", class: "btn btn-secondary cminus" %>
            <% end %>
            <%= link_to raw("<i class=\"fas fa-plus\"></i>"), addtocart_path(cart.id), method: "get", class: "btn btn-secondary cplus" %>
          </div>
      </div>
      <% @total += cart.total_per_item %>
      <div class="px-3 my-3 text-center">
        <div class="cart-item-label">Subtotal</div>
        <span class="text-xl font-weight-medium "><%= cart.total_per_item %>.00€</span>
      </div>        
    </div>
  <% end %>

  <!--  Subtotal-->
  <div class="d-sm-flex justify-content-between align-items-center text-center text-sm-left">
    <!-- Right Aligned -->
    <div class="animated-digits" data-number="<%= @total %>">
      <h5 class="animated-digits-digit">€<span>0</span></h5>
      <p class="animated-digits-text">Total Cost</p>
    </div>
  </div>

  <!-- Buttons-->
  <hr class="my-2">
  <div class="row pt-3 pb-5 mb-2">
    <%= form_tag({controller: "carts", action: "payment"}, method: "get") do %>
      <article>
        <% if flash[:error].present? %>
          <div id="error_explanation">
            <p><%= flash[:error] %></p>
          </div>
        <% end %>
        <label class="amount">
          <span></span>
        </label>
      </article>

      <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
              data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
              data-description="Achat"
              data-label="Checkout"
              data-amount=@total
              data-locale="auto">
      </script>
      <script>document.getElementsByClassName("stripe-button-el")[0].style.display = 'none';</script>
      <button type="submit" class="btn btn-accent mt-0 btn-sm">Checkout</button>
    <% end %>
  </div>
</div>

app/views/carts/payment.html.erb
<h1>TO BE FORMATTED OFC</h1>
<h2>Your payment has been validated</h2>
<h3>New order: <%= Order.find_by_stripe_id(params[:stripeToken]).created_at %></h3>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Order</th>
      <th>Item</th>
      <th>Quantity</th>
    </tr>
  </thead>

  	<tbody>
	<% Cart.where(order_id: Order.find_by_stripe_id(params[:stripeToken]).id).each do |cart_item| %>
		<tr>
	        <td><%= cart_item.user %></td>
	        <td><%= cart_item.order_id %></td>
	        <td><%= cart_item.item %></td>
	        <td><%= cart_item.quantity %></td>
	    </tr>
	<% end %>
	</tbody>
</table>