config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'
  get 'errors/internal_server_error'
  root 'items#index' 
  get '/home/contact', to: 'home#contact', as: 'contacts'
  get '/home/about_us', to: 'home#about_us', as: 'about_us'
  get '/home/faq', to: 'home#faq', as: 'faq'
  get '/add_to_carts/:id' => 'carts#additem', as: 'addtocart'
  get '/remove_from_carts/:id' => 'carts#removeitem', as: 'removefromcart'



  devise_for :users,
    :controllers => {:registrations => "registrations"},
    path: '',
    path_names: { sign_up: 'Create Account', sign_in: 'Login', sign_out: 'Logout', password: 'Reset Password'}
  devise_scope :user do 
    get "/my_profile" => "registrations#show"
    get "/my_profile/security" => "registrations#security"
    resources :wishlists

  end

  resources :reviews
  resources :items

  get '/carts/payment' => 'carts#payment'
  resources :carts
  resources :orders
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
end

app/models/item.rb
class Item < ApplicationRecord
	validates :title, :description, :price, :image_url, presence: true

  has_many :carts
  has_many :wishlists
  has_many :reviews
  belongs_to :breed
  belongs_to :admin, class_name: "User"
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.page(params[:page]).per(6).without_count
    @reviews = Review.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @reviews = Review.all.where(item_id: @item).order('created_at DESC')
    @users = User.all
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to root_path, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.fetch(:item, {})
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<!-- Page Content-->
<div class="container-fluid pb-5 mb-3">
  <div class="row justify-content-center">
    <div class="col-xl-10">
      <!-- Pagination-->
      <div class="pagination">
        <div><a class="prev-btn" href="<%= path_to_prev_page @items %>"><i class="fas fa-angle-double-left"></i>Previous page</a></div>
        <div><a class="next-btn" href="<%= path_to_next_page @items %>">Next page<i class="fas fa-angle-double-right"></i></a></div>
      </div>

      <!-- Shop Grid-->
      <div class="row">
        <!-- Product-->
        <% @items.each do |element| %>
          <div class="col-lg-4 col-md-12 col-sm-12 mb-30">
            <div class="product-card mx-auto mb-3 mw-100">
              <div class="product-head d-flex justify-content-between align-items-center">
                <span class="badge badge-danger">On Sale</span>
                <div>
                  <% sumrating = 0 %>
                  <% @reviews.where(item_id: element.id).each do |review| %>
                    <% sumrating += review.rating %>
                  <% end %>
                  <% if @reviews.where(item_id: element.id).length == 0 %>
                    <% rate = 0 %>
                  <% else %>
                    <% rate = sumrating/@reviews.where(item_id: element.id).length %>
                  <% end %>
                  <div>
                    <div class="rating-stars">
                      <% rate.round.times do %>
                        <i class="fas fa-star active"></i>
                      <% end %>
                    </div>
                    <div class="rating-stars">
                      <% (5 - rate.round).times do %>
                        <i class="fas fa-star"></i>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
              <%= link_to element do %>
                <img src="<%= element.image_url%>" class="img-fluid product-thumb w-100" style="height:250px"/>
             <% end %>
              <div class="product-card-body">
                <a class="product-meta"><%= Breed.find(element.breed_id).name %></a>
                <h5 class="product-title">
                  <%= link_to element.title, controller: "items", action: "show", id: element %>
                </h5>
                <span class="product-price"><%= element.price.to_i %>€</span>
              </div>
              <div class="m-1">
                <hr />
                <div class="d-flex justify-content-between align-items-center my-1">
                  <div>
                    <a class="scroll-to post-author" href="#">
                      <div class="post-author-avatar">
                        <div>
                          <%if User.where(is_admin: true).first.avatar.attached?%>
                            <%= image_tag User.find_by_id(element.admin_id).avatar, alt: User.find_by_id(element.admin_id).fullname, style: "width:28px;height:28px;border-radius:50%;" %>
                          <%else%>
                            <%= image_tag("default_avatar.svg", :style => "width:28px;height:28px;border-radius:50%;") %> 
                          <%end%>
                        </div>
                      </div>
                      <div class="post-author-name">Posted by: <%= User.find_by_id(element.admin_id).fullname %> </div>
                    </a>
                  </div>
                  <div class="post-meta">
                    <span class="text-sm"><i class="far fa-clock"></i><%= element.created_at.strftime("%B %d, %Y") %></span>
                  </div>
                </div>
                <hr />
              </div>
              <% if user_signed_in? %>
                <div class="product-buttons-wrap">
                  <div class="product-buttons">
                    <div class="product-button">
                        <%= form_for Wishlist.new do |f| %>
                        <%= f.hidden_field :item_id, :value => element.id %>
                        <%= button_tag(type: "submit", class: "product-button") do %>
                          <i class="fas fa-heart"></i><% end %>
                        <% end %>
                    </div>
                    <% if Cart.where(user_id: current_user.id).where(order_id: nil).map(&:item_id).include?(element.id) %> 
                      <%= link_to raw("<i class=\"fas fa-plus\"></i>"), addtocart_path(Cart.where(user_id: current_user.id).where(order_id: nil).where(item_id: element.id).ids), method: "get", class: "btn btn-secondary cplus" %> 
                    <% else %>  
                      <%= form_for Cart.new do |f| %>
                        <%= f.hidden_field :item_id, :value => element.id %>
                        <%= button_tag(type: "submit", class: "product-button") do %>
                          <i class="fas fa-cart-plus"></i>
                        <% end %>
                      <% end %>
                    <% end %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
      <!-- Pagination-->
      <div class="pagination ">
        <div><a class="prev-btn" href="<%= path_to_prev_page @items %>"><i class="fas fa-angle-double-left"></i>Previous page</a></div>
        <div><a class="next-btn" href="<%= path_to_next_page @items %>">Next page<i class="fas fa-angle-double-right"></i></a></div>
      </div>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<!-- Page Content-->
<div class="container mb-2">
  <div class="row">
    <!-- Product Gallery-->
    <div class="col-md-6 pb-5">
      <div class="product-gallery">
        <span class="badge badge-danger text-md font-weight-normal">On Sale</span>
        <div class="product-carousel owl-carousel">
          <a data-fancybox="gallery1" data-hash="one"><img src="<%= @item.image_url%>"></a>
        </div>
      </div>
    </div>
    <!-- Product Info-->
    <div class="col-md-6 pb-5">
      <div class="product-meta">
        <i class="fas fa-bookmark"></i><a>Categories: </a><a href="#"><%= Breed.find(@item.breed_id).name %></a>
      </div>
      <div class="m-1">
        <hr />
        <div class="d-flex justify-content-between align-items-center my-1">
          <div>
            <a class="scroll-to post-author" href="#">
              <div class="post-author-avatar">
                <div>
                  <%if User.where(is_admin: true).first.avatar.attached?%>
                    <%= image_tag User.find_by_id(@item.admin_id).avatar, alt: User.find_by_id(@item.admin_id).fullname, style: "width:28px;height:28px;border-radius:50%;" %>
                  <%else%>
                    <%= image_tag("default_avatar.svg", :style => "width:28px;height:28px;border-radius:50%;") %> 
                  <%end%>
                </div>
              </div>
              <div class="post-author-name">Posted by: <%= User.find_by_id(@item.admin_id).fullname %> </div>
            </a>
          </div>
          <div class="post-meta">
            <span class="text-sm"><i class="far fa-clock"></i><%= @item.created_at.strftime("%B %d, %Y") %></span>
          </div>
        </div>
        <hr />
      </div>
      <h2 class="h3 font-weight-bold"><%= @item.title %></h2>
      <h3 class="h4 font-weight-light"><%= @item.price.to_i %>€</h3>
      <p class="text-muted">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta voluptatibus quos ea dolore rem, molestias laudantium et explicabo...
        <a href='#details' class='scroll-to'>More info</a>
      </p>
      <% if user_signed_in? %>
        <div class="row align-items-end pb-4">
          <div class="col-sm-4">
            <div class="form-group mb-0">
              <label for="quantity">Quantity</label>
              <select class="form-control" id="quantity">
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
              </select>
            </div>
          </div>
          <div class="col-sm-8">
            <div class="pt-4 hidden-sm-up"></div>
            <button class="btn btn-primary btn-block m-0" data-toast data-toast-type="success" data-toast-position="topRight" data-toast-icon="fe-icon-check-circle" data-toast-title="Product" data-toast-message="successfuly added to cart!">
              <i class="fas fa-cart-arrow-down"></i>Add to Cart
            </button>
          </div>
        </div>
      <% end %>
      <hr class="mb-2">
      <div class="d-flex flex-wrap justify-content-between align-items-center">
        <% if user_signed_in? %>
          <div class="mt-2 mb-2">
            <button class="btn btn-danger btn-sm my-2 mr-1" data-toast data-toast-type="info" data-toast-position="topRight" data-toast-icon="fe-icon-info" data-toast-title="Product" data-toast-message="added to your wishlist!">
              <i class="fas fa-heart"></i>Wishlist
            </button>
          </div>
        <% end %>
        <div class="mt-2 mb-2">
          <span class="text-muted d-inline-block align-middle mb-2">Share:&nbsp;&nbsp;</span>
          <div class="d-inline-block">
            <a class="social-btn sb-style-3 sb-facebook my-1" href="https://www.facebook.com/" data-toggle="tooltip" data-placement="top" title="Facebook"><i class="fab fa-facebook-f"></i></a>
            <a class="social-btn sb-style-3 sb-twitter my-1" href="https://twitter.com/login?lang=fr" data-toggle="tooltip" data-placement="top" title="Twitter"><i class="fab fa-twitter"></i></a>
            <a class="social-btn sb-style-3 sb-instagram my-1" href="https://www.instagram.com/?hl=fr" data-toggle="tooltip" data-placement="top" title="Instagram"><i class="fab fa-instagram"></i></a>
            <a class="social-btn sb-style-3 sb-google-plus my-1 mr-0" href="https://plus.google.com/about?hl=fr" data-toggle="tooltip" data-placement="top" title="Google +"><i class="fab fa-google-plus-g"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Product Details-->
<div class="bg-secondary pt-5 pb-4" id="details">
  <div class="container py-2">
    <div class="row">
      <div class="col-lg-3 col-md-6">
        <h3 class="h6">Details</h3>
        <p class="mb-4 pb-2">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat.</p>
      </div>
      <div class="col-lg-3 col-md-6">
        <h3 class="h6">Features</h3>
        <p class="mb-4 pb-2">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat.</p>
      </div>
      <div class="col-lg-3 col-md-6">
        <h3 class="h6">Specifications</h3>
        <p class="mb-4 pb-2">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat.</p>
      </div>
      <div class="col-lg-3 col-md-6">
        <h3 class="h6">Shipping Options:</h3>
        <p class="mb-4 pb-2">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat.</p>
      </div>
    </div>
  </div>
</div>

<!-- Reviews-->
<div class="container pt-5">
  <div class="row pt-2">
    <div class="col-md-4 pb-5 mb-3">
      <div class="card border-default">
        <div class="card-body">
          <div class="text-center">
            <% countfive = 0 %><% countfour = 0 %><% countthree = 0 %><% counttwo = 0 %><% countone = 0 %><% sumrating = 0 %><% indice = 100/@reviews.length %>
            <% @reviews.each do |review| %>
              <% sumrating += review.rating %>
              <% case review.rating %>
                <% when 5 %>
                  <% countfive +=1 %>
                <% when 4 %>
                  <% countfour +=1 %>
                <% when 3 %>
                  <% countthree +=1 %>
                <% when 2 %>
                  <% counttwo +=1 %>
                <% when 1 %>
                  <% countone +=1 %>
                <% else %>
              <% end %>
            <% end %>
            <% rate = sumrating / @reviews.length %>
            <h4>Note : <%= rate.round %></h4>
            <h5 class='text-muted'>Avis : <%= @reviews.length %></h5>
            <div>
              <div class="rating-stars">
                <% rate.round.times do %>
                  <i class="fas fa-star active"></i>
                <% end %>
                <div class="rating-stars">
                  <% (5 - rate.round).times do %>
                    <i class="fas fa-star"></i>
                  <% end %>
                </div>
              </div>
              <div class="pt-3">
                <span class="progress-label">5 stars <span class='text-muted'>- <%= countfive %></span></span>
                <div class="progress progress-style-3 mb-3">
                  <div class="progress-bar bg-warning" role="progressbar" style="width: <%= countfive*indice %>%;" aria-valuenow="<%= countfive*indice %>" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <span class="progress-label">4 stars <span class='text-muted'>- <%= countfour %></span></span>
                <div class="progress progress-style-3 mb-3">
                  <div class="progress-bar bg-warning" role="progressbar" style="width: <%= countfour*indice %>%;;" aria-valuenow="<%= countfour*indice %>" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <span class="progress-label">3 stars <span class='text-muted'>- <%= countthree %></span></span>
                <div class="progress progress-style-3 mb-3">
                  <div class="progress-bar bg-warning" role="progressbar" style="width: <%= countthree*indice %>%;" aria-valuenow="<%= countthree*indice %>" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <span class="progress-label">2 stars <span class='text-muted'>- <%= counttwo %></span></span>
                <div class="progress progress-style-3 mb-3">
                  <div class="progress-bar bg-warning" role="progressbar" style="width: <%= counttwo*indice %>%;" aria-valuenow="<%= counttwo*indice %>" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <span class="progress-label">1 stars <span class='text-muted'>- <%= countone %></span></span>
                <div class="progress progress-style-3 mb-3">
                  <div class="progress-bar bg-warning" role="progressbar" style="width: <%= countone*indice %>%;" aria-valuenow="<%= countone*indice %>" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </div>

              <!-- Modal -->
              <div class="pt-3">
                <a class="btn btn-warning btn-block" data-toggle="modal" data-target="#leaveReview">Leave a Review</a>
              </div>
              <div class="modal fade" id="leaveReview" role="dialog">
                <div class="modal-dialog">
                  <!-- Modal content-->
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                      <h4 class="modal-title">Leave a review!</h4>
                    </div>
                    <div class="modal-body">
                      <!-- A compléter -->
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>    
    <div class="col-md-8 pb-5 mb-3">
      <div class="d-flex flex-wrap justify-content-between pb-2">
        <h3 class="h4">Latest Reviews</h3><a class="btn btn-primary btn-sm" href="#">View All Reviews</a>
      </div>
      <!-- Review-->
      <div class="blockquote comment mb-4 row">
        <% @reviews.each do |review| %>
          <div class="card-body">  
            <div class="d-flex flex-wrap justify-content-between pb-2">
              <div class="col-9">
                <h6 class="text-lg mb-0"><%= review.title %></h6>
              </div>
              <!-- Stars counter -->
              <div class="col-3">
                <div class="rating-stars" >
                  <% review.rating.times do %>
                    <i class="fas fa-star active"></i>
                  <% end %>
                  <% (5- review.rating).times do %>
                    <i class="fas fa-star"></i>
                  <% end %>
                </div>
              </div>
            </div>
            <div class="d-flex flex-wrap justify-content-between pb-2">   
              <div class="col-9">
                <%= review.content %>
              </div>
              <div class=" col-3">
                <div class="d-table-cell align-middle pl-2">
                  <div class="blockquote-footer"> 
                    <% @users.each do |user| %>
                      <% if user.id == review.user_id %> 
                        <%= user.username %> 
                      <% end %>
                    <% end %>
                    <cite> <%= review.created_at.strftime("%FT") %></cite>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>