config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'
  get 'errors/internal_server_error'
  root 'items#index' 
  get '/home/contact', to: 'home#contact', as: 'contacts'
  get '/home/about_us', to: 'home#about_us', as: 'about_us'
  get '/home/faq', to: 'home#faq', as: 'faq'
  get '/add_to_carts/:id' => 'carts#additem', as: 'addtocart'
  get '/remove_from_carts/:id' => 'carts#removeitem', as: 'removefromcart'



  devise_for :users,
    :controllers => {:registrations => "registrations"},
    path: '',
    path_names: { sign_up: 'Create Account', sign_in: 'Login', sign_out: 'Logout', password: 'Reset Password'}
  devise_scope :user do 
    get "/my_profile" => "registrations#show"
    get "/my_profile/security" => "registrations#security"
    resources :wishlists

  end

  resources :reviews
  resources :items

  get '/carts/payment' => 'carts#payment'
  resources :carts
  resources :orders
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
end

app/views/layouts/_footer.html.erb
<footer class="bg-dark pt-3 mt-3">
  <div class="container">
    <div class="row">
      <div class="col-lg-3 pb-4"><a class="navbar-brand d-inline-block mb-4" href="<%= root_path %>"><%= image_tag("meow.png") %></a></div>
      <div class="col-lg-9">
        <h2 class="text-white">The Kittens</h2>
        <div class="widget widget-light-skin mb-0">
          <h4 class="widget-title">Useful Links</h4>
        </div>
        <div class="row">
          <div class="col-md-3">
            <div class="widget widget-categories widget-light-skin">
              <ul>
                <li><a href="<%= about_us_path %>">About Us</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-3">
            <div class="widget widget-categories widget-light-skin">
              <ul>
                <li><a href="<%= contacts_path %>">Contact</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-3">
            <div class="widget widget-categories widget-light-skin">
              <ul>
                <li><a href="<%= faq_path%>">FAQ</a></li>
              </ul>
            </div>
          </div>
          <p class="text-sm text-white opacity-50 pl-3">
            Made with love by Guillaume CHRISTE, Gérard GOACHET, Selmen M'HAMDI & Lauren OLIVIER
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!-- Off-Canvas Shopping Cart-->
<% if user_signed_in? %>
  <div class="offcanvas-container is-triggered offcanvas-container-reverse " id="shopping-cart">
    <span class="offcanvas-close"><i class="far fa-times-circle"></i>
    </span>
    <div class="px-4">
      <h6>Your Cart</h6>
      <div class="widget widget-cart pt-2">
        <% total = 0 %>
        <% i = 0 %>
        <% total_quantity = 0 %>
        <% Cart.where(user_id: current_user.id).where(order_id: nil).order(:id).each do |cartelement| %>
          <% total += cartelement.total_per_item %>
          <% total_quantity += cartelement.quantity %>
        <% end %>
        <span class="text-sm text-muted">Total Price: <%= total %> .00 € with <%= total_quantity %> articles </span>
        <div class="d-flex justify-content-between ptexi-3">
          <a class="btn btn-primary btn-block btn-sm mr-2" href="<%= carts_path%>">View Cart / Checkout</a>
        </div>
        <hr class="mt-2 mb-2 border border-accent" />
        <% Cart.where(user_id: current_user.id).where(order_id: nil).order(:id).each do |cartelement| %>
          <a class="featured-product" data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/carts/<%= cartelement.id %>"><span class="remove-product"><i class="far fa-times-circle"></i></span></a>
          <% i +=1 %>
          <div class="featured-product-thumb">
            <img src="<%= Item.find(cartelement.item_id).image_url %>" alt="Product Image"/>
          </div>
          <div class="featured-product-info">
            <h5 class="featured-product-title"><%= Item.find(cartelement.item_id).title %></h5>
            <h5 class="featured-product-price"> <%= Item.find(cartelement.item_id).price.to_i %>.00 € </h5>
            <h5 class="featured-product-price">x<%= cartelement.quantity %> | In total : <%= cartelement.total_per_item %>.00 €</h5>
            <h5 class="featured-product-title"></h5>
          </div>
        <% end %>
      </div>
    </div>
  </div>   
<% end %>
<!-- Navbar: Default-->
<!-- Remove "navbar-sticky" class to make navigation bar scrollable with the page.-->
<header class="navbar-wrapper navbar-sticky mb-3">
  <div class="d-table-cell align-middle pr-md-3">
    <a class="navbar-brand mr-1" href="<%= root_path %>"><%= image_tag("logo.png") %></a>
  </div>
  <div class="d-table-cell w-100 align-middle pl-md-3">
    <div class="navbar-top d-none d-lg-flex justify-content-between align-items-center">
      <div>
        <a class="navbar-link mr-3" href="mailto:support@kittens.com"><i class="far fa-envelope"></i>support@kittens.com</a>
      </div>
      <div>
        <ul class="list-inline mb-0">
          <% if user_signed_in? %>
            <a class="navbar-link" href="<%= my_profile_path %>">
              <div>
                <%if current_user.avatar.attached?%>
                  <%= image_tag current_user.avatar, alt: current_user.fullname, :style => "width:30px;height:30px;border-radius:50%;" %>
                <%else%>
                  <%= image_tag("default_avatar.svg", :style => "width:30px;height:30px;border-radius:50%;") %> 
                <%end%>
              </div>
            </a>
            <a href="<%= destroy_user_session_path%>" class="btn btn-style-6 btn-danger btn-sm" data-method="DELETE">Logout</a>
          <% else %>
            <a class="navbar-link" href="<%= my_profile_path %>"><i class="far fa-user"></i></a>
            <li class="dropdown-toggle mr-2 navbar-link">Login or Create account
              <div class="dropdown-menu right-aligned p-3 text-center" style="min-width: 200px;">
                <p class="text-sm opacity-70">Sign in to your account or register new one to have full control over your orders, receive bonuses and more.</p>
                <a class="btn btn-primary btn-sm btn-block" href="<%= new_user_session_path %>">Sign In</a>
                <p class="text-sm text-muted mt-3 mb-0">New customer? <a href="<%=new_user_registration_path %>">Register</a></p>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="navbar justify-content-end justify-content-lg-between">
      <!-- Search-->
      <form class="search-box" method="get">
        <input type="text" id="site-search" placeholder="Type A or C to see suggestions">
        <span class="search-close">
          <i class="fe-icon-x"></i></span>
      </form>
      <!-- Main Menu-->
      <ul class="navbar-nav d-none d-lg-block">
        <!-- Home-->
        <li class="nav-item active"><a class="nav-link" href="<%= root_path %>">Home</a></li>
        <% if user_signed_in? %>
         <!-- My wishlist -->
         <li class="nav-item "><a class="nav-link" href="<%= wishlists_path %>">My Wishlist</a></li>
        <% end %>
        <!-- FAQ-->
        <li class="nav-item "><a class="nav-link" href="<%= faq_path%>">FAQ</a></li>
        <!-- ABOUT US-->
        <li class="nav-item "><a class="nav-link" href="<%= about_us_path %>">About Us</a></li>
        <!-- CONTACTS-->
        <li class="nav-item "><a class="nav-link" href="<%= contacts_path %>">Contact</a></li>
      </ul>
      <div>
        <ul class="navbar-buttons d-inline-block align-middle mr-lg-2">
          <li class="d-block d-lg-none">
            <a href="#mobile-menu" data-toggle="offcanvas">
              <i class="fe-icon-menu"></i>
            </a>
          </li>
          <% if user_signed_in? %>
            <li>
              <a href="#shopping-cart" data-toggle="offcanvas">
                <i class="fas fa-cart-arrow-down"></i>
              </a>
              <span class="badge badge-danger"><%= i %></span>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheKittens</title>
    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
    <%= favicon_link_tag asset_path('favicon.png') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

  </head>

  <body>

    <%= render 'layouts/header' %>

    <% flash.each do |key, value| %>
      <% unless value.blank? %>
        <div class="iziToast-wrapper iziToast-wrapper-topRight">
          <div class="iziToast-capsule" style="height: auto;">
            <% if key == "alert"  %>
              <div class="iziToast bounceInLeft iziToast-theme-light iziToast-color-red iziToast-animateInside iziToast-opened" id="<%=key%>">
                <div class="iziToast-body iziToast-red" style="padding-left: 33px;">
                  <button id="close-toast-popup" class="m-1 p-0 btn-popup iziToast-red">&times;</button>
                  <div class="iziToast-texts">
                    <strong class="slideIn" style="margin-right: 10px;">
                      <i class="fas fa-ban"></i>&nbsp;&nbsp;Alert
                    </strong>
                    <p class="slideIn"><%=value%></p>
                  </div>
                </div>
              </div>
            <% elsif key == "warning"  %>
              <div data-izitoast-ref="1551970854150" class="iziToast bounceInLeft iziToast-theme-light iziToast-color-orange iziToast-animateInside iziToast-opened" id="<%=key%>">
                <div class="iziToast-body iziToast-orange" style="padding-left: 33px;">
                  <button id="close-toast-popup" class="m-1 p-0 btn-popup iziToast-orange">&times;</button>
                  <div class="iziToast-texts">
                    <strong class="slideIn" style="margin-right: 10px;">
                      <i class="fas fa-exclamation-triangle"></i>&nbsp;&nbsp;Warning
                    </strong>
                    <p class="slideIn"><%=value%></p>
                  </div>
                </div>
              </div>
            <% elsif key == "info"  %>
              <div data-izitoast-ref="1551970854150" class="iziToast bounceInLeft iziToast-theme-light iziToast-color-blue iziToast-animateInside iziToast-opened" id="<%=key%>">
                <div class="iziToast-body iziToast-blue" style="padding-left: 33px;">
                  <button id="close-toast-popup" class="m-1 p-0 btn-popup iziToast-blue">&times;</button>
                  <div class="iziToast-texts">
                    <strong class="slideIn" style="margin-right: 10px;">
                      <i class="fas fa-info-circle"></i>&nbsp;&nbsp;Information
                    </strong>
                    <p class="slideIn"><%=value%></p>
                  </div>
                </div>
              </div>
            <% elsif key == "notice"  %>
              <div data-izitoast-ref="1551970854150" class="iziToast bounceInLeft iziToast-theme-light iziToast-color-green iziToast-animateInside iziToast-opened" id="<%=key%>">
                <div class="iziToast-body iziToast-green" style="padding-left: 33px;">
                  <button id="close-toast-popup" class="m-1 p-0 btn-popup iziToast-green">&times;</button>
                  <div class="iziToast-texts">
                    <strong class="slideIn" style="margin-right: 10px;">
                      <i class="far fa-check-circle"></i>&nbsp;&nbsp;Success
                    </strong>
                    <p class="slideIn"><%=value%></p>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>

    <%= yield %>

    <%= render 'layouts/footer' %>

  </body>
</html>